# Generated by Django 3.0.3 on 2020-09-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_firstname', models.CharField(max_length=20)),
                ('tutor_lastname', models.CharField(max_length=20)),
                ('tutor_email', models.EmailField(max_length=254)),
                ('tutor_teach_field', models.CharField(max_length=50)),
            ],
        ),
    ]
